var annotated_dup =
[
    [ "NATS", "namespace_n_a_t_s.html", [
      [ "Client", "namespace_n_a_t_s_1_1_client.html", [
        [ "JetStream", "namespace_n_a_t_s_1_1_client_1_1_jet_stream.html", [
          [ "BaseConsumeOptions", "class_n_a_t_s_1_1_client_1_1_jet_stream_1_1_base_consume_options.html", null ],
          [ "ConsumeOptions", "class_n_a_t_s_1_1_client_1_1_jet_stream_1_1_consume_options.html", "class_n_a_t_s_1_1_client_1_1_jet_stream_1_1_consume_options" ],
          [ "ConsumerLimits", "class_n_a_t_s_1_1_client_1_1_jet_stream_1_1_consumer_limits.html", "class_n_a_t_s_1_1_client_1_1_jet_stream_1_1_consumer_limits" ],
          [ "External", "class_n_a_t_s_1_1_client_1_1_jet_stream_1_1_external.html", "class_n_a_t_s_1_1_client_1_1_jet_stream_1_1_external" ],
          [ "FetchConsumeOptions", "class_n_a_t_s_1_1_client_1_1_jet_stream_1_1_fetch_consume_options.html", "class_n_a_t_s_1_1_client_1_1_jet_stream_1_1_fetch_consume_options" ],
          [ "IBaseConsumerContext", "interface_n_a_t_s_1_1_client_1_1_jet_stream_1_1_i_base_consumer_context.html", "interface_n_a_t_s_1_1_client_1_1_jet_stream_1_1_i_base_consumer_context" ],
          [ "IConsumerContext", "interface_n_a_t_s_1_1_client_1_1_jet_stream_1_1_i_consumer_context.html", "interface_n_a_t_s_1_1_client_1_1_jet_stream_1_1_i_consumer_context" ],
          [ "IFetchConsumer", "interface_n_a_t_s_1_1_client_1_1_jet_stream_1_1_i_fetch_consumer.html", "interface_n_a_t_s_1_1_client_1_1_jet_stream_1_1_i_fetch_consumer" ],
          [ "IIterableConsumer", "interface_n_a_t_s_1_1_client_1_1_jet_stream_1_1_i_iterable_consumer.html", "interface_n_a_t_s_1_1_client_1_1_jet_stream_1_1_i_iterable_consumer" ],
          [ "IJetStream", "interface_n_a_t_s_1_1_client_1_1_jet_stream_1_1_i_jet_stream.html", "interface_n_a_t_s_1_1_client_1_1_jet_stream_1_1_i_jet_stream" ],
          [ "IJetStreamManagement", "interface_n_a_t_s_1_1_client_1_1_jet_stream_1_1_i_jet_stream_management.html", "interface_n_a_t_s_1_1_client_1_1_jet_stream_1_1_i_jet_stream_management" ],
          [ "IJetStreamPullAsyncSubscription", "interface_n_a_t_s_1_1_client_1_1_jet_stream_1_1_i_jet_stream_pull_async_subscription.html", null ],
          [ "IJetStreamPullSubscription", "interface_n_a_t_s_1_1_client_1_1_jet_stream_1_1_i_jet_stream_pull_subscription.html", "interface_n_a_t_s_1_1_client_1_1_jet_stream_1_1_i_jet_stream_pull_subscription" ],
          [ "IJetStreamPushAsyncSubscription", "interface_n_a_t_s_1_1_client_1_1_jet_stream_1_1_i_jet_stream_push_async_subscription.html", null ],
          [ "IJetStreamPushSyncSubscription", "interface_n_a_t_s_1_1_client_1_1_jet_stream_1_1_i_jet_stream_push_sync_subscription.html", null ],
          [ "IMessageConsumer", "interface_n_a_t_s_1_1_client_1_1_jet_stream_1_1_i_message_consumer.html", "interface_n_a_t_s_1_1_client_1_1_jet_stream_1_1_i_message_consumer" ],
          [ "IOrderedConsumerContext", "interface_n_a_t_s_1_1_client_1_1_jet_stream_1_1_i_ordered_consumer_context.html", null ],
          [ "IStreamContext", "interface_n_a_t_s_1_1_client_1_1_jet_stream_1_1_i_stream_context.html", "interface_n_a_t_s_1_1_client_1_1_jet_stream_1_1_i_stream_context" ],
          [ "MetaData", "class_n_a_t_s_1_1_client_1_1_jet_stream_1_1_meta_data.html", "class_n_a_t_s_1_1_client_1_1_jet_stream_1_1_meta_data" ],
          [ "Mirror", "class_n_a_t_s_1_1_client_1_1_jet_stream_1_1_mirror.html", "class_n_a_t_s_1_1_client_1_1_jet_stream_1_1_mirror" ],
          [ "NATSJetStreamException", "class_n_a_t_s_1_1_client_1_1_jet_stream_1_1_n_a_t_s_jet_stream_exception.html", "class_n_a_t_s_1_1_client_1_1_jet_stream_1_1_n_a_t_s_jet_stream_exception" ],
          [ "Placement", "class_n_a_t_s_1_1_client_1_1_jet_stream_1_1_placement.html", "class_n_a_t_s_1_1_client_1_1_jet_stream_1_1_placement" ],
          [ "PullRequestOptions", "class_n_a_t_s_1_1_client_1_1_jet_stream_1_1_pull_request_options.html", "class_n_a_t_s_1_1_client_1_1_jet_stream_1_1_pull_request_options" ],
          [ "Republish", "class_n_a_t_s_1_1_client_1_1_jet_stream_1_1_republish.html", "class_n_a_t_s_1_1_client_1_1_jet_stream_1_1_republish" ],
          [ "Source", "class_n_a_t_s_1_1_client_1_1_jet_stream_1_1_source.html", "class_n_a_t_s_1_1_client_1_1_jet_stream_1_1_source" ],
          [ "SourceBase", "class_n_a_t_s_1_1_client_1_1_jet_stream_1_1_source_base.html", "class_n_a_t_s_1_1_client_1_1_jet_stream_1_1_source_base" ],
          [ "SubjectTransform", "class_n_a_t_s_1_1_client_1_1_jet_stream_1_1_subject_transform.html", "class_n_a_t_s_1_1_client_1_1_jet_stream_1_1_subject_transform" ],
          [ "SubscribeOptions", "class_n_a_t_s_1_1_client_1_1_jet_stream_1_1_subscribe_options.html", "class_n_a_t_s_1_1_client_1_1_jet_stream_1_1_subscribe_options" ]
        ] ],
        [ "ObjectStore", "namespace_n_a_t_s_1_1_client_1_1_object_store.html", [
          [ "ObjectInfo", "class_n_a_t_s_1_1_client_1_1_object_store_1_1_object_info.html", null ],
          [ "ObjectLink", "class_n_a_t_s_1_1_client_1_1_object_store_1_1_object_link.html", null ],
          [ "ObjectMeta", "class_n_a_t_s_1_1_client_1_1_object_store_1_1_object_meta.html", null ],
          [ "ObjectMetaOptions", "class_n_a_t_s_1_1_client_1_1_object_store_1_1_object_meta_options.html", null ]
        ] ],
        [ "Rx", "namespace_n_a_t_s_1_1_client_1_1_rx.html", [
          [ "INATSObservable", "interface_n_a_t_s_1_1_client_1_1_rx_1_1_i_n_a_t_s_observable.html", null ],
          [ "NATSObservable", "class_n_a_t_s_1_1_client_1_1_rx_1_1_n_a_t_s_observable.html", "class_n_a_t_s_1_1_client_1_1_rx_1_1_n_a_t_s_observable" ],
          [ "NATSObservableSubscription", "class_n_a_t_s_1_1_client_1_1_rx_1_1_n_a_t_s_observable_subscription.html", null ],
          [ "NATSRxException", "class_n_a_t_s_1_1_client_1_1_rx_1_1_n_a_t_s_rx_exception.html", null ]
        ] ],
        [ "Service", "namespace_n_a_t_s_1_1_client_1_1_service.html", [
          [ "Discovery", "class_n_a_t_s_1_1_client_1_1_service_1_1_discovery.html", "class_n_a_t_s_1_1_client_1_1_service_1_1_discovery" ],
          [ "Endpoint", "class_n_a_t_s_1_1_client_1_1_service_1_1_endpoint.html", "class_n_a_t_s_1_1_client_1_1_service_1_1_endpoint" ],
          [ "EndpointStats", "class_n_a_t_s_1_1_client_1_1_service_1_1_endpoint_stats.html", "class_n_a_t_s_1_1_client_1_1_service_1_1_endpoint_stats" ],
          [ "Group", "class_n_a_t_s_1_1_client_1_1_service_1_1_group.html", "class_n_a_t_s_1_1_client_1_1_service_1_1_group" ],
          [ "InfoResponse", "class_n_a_t_s_1_1_client_1_1_service_1_1_info_response.html", "class_n_a_t_s_1_1_client_1_1_service_1_1_info_response" ],
          [ "PingResponse", "class_n_a_t_s_1_1_client_1_1_service_1_1_ping_response.html", null ],
          [ "Service", "class_n_a_t_s_1_1_client_1_1_service_1_1_service.html", "class_n_a_t_s_1_1_client_1_1_service_1_1_service" ],
          [ "ServiceBuilder", "class_n_a_t_s_1_1_client_1_1_service_1_1_service_builder.html", "class_n_a_t_s_1_1_client_1_1_service_1_1_service_builder" ],
          [ "ServiceEndpoint", "class_n_a_t_s_1_1_client_1_1_service_1_1_service_endpoint.html", "class_n_a_t_s_1_1_client_1_1_service_1_1_service_endpoint" ],
          [ "ServiceException", "class_n_a_t_s_1_1_client_1_1_service_1_1_service_exception.html", "class_n_a_t_s_1_1_client_1_1_service_1_1_service_exception" ],
          [ "ServiceMsg", "class_n_a_t_s_1_1_client_1_1_service_1_1_service_msg.html", "class_n_a_t_s_1_1_client_1_1_service_1_1_service_msg" ],
          [ "ServiceMsgHandlerEventArgs", "class_n_a_t_s_1_1_client_1_1_service_1_1_service_msg_handler_event_args.html", null ],
          [ "ServiceResponse", "class_n_a_t_s_1_1_client_1_1_service_1_1_service_response.html", "class_n_a_t_s_1_1_client_1_1_service_1_1_service_response" ],
          [ "StatsResponse", "class_n_a_t_s_1_1_client_1_1_service_1_1_stats_response.html", "class_n_a_t_s_1_1_client_1_1_service_1_1_stats_response" ]
        ] ],
        [ "AsyncSubscription", "class_n_a_t_s_1_1_client_1_1_async_subscription.html", "class_n_a_t_s_1_1_client_1_1_async_subscription" ],
        [ "Connection", "class_n_a_t_s_1_1_client_1_1_connection.html", "class_n_a_t_s_1_1_client_1_1_connection" ],
        [ "ConnectionFactory", "class_n_a_t_s_1_1_client_1_1_connection_factory.html", "class_n_a_t_s_1_1_client_1_1_connection_factory" ],
        [ "ConnEventArgs", "class_n_a_t_s_1_1_client_1_1_conn_event_args.html", "class_n_a_t_s_1_1_client_1_1_conn_event_args" ],
        [ "ConnJsSubEventArgs", "class_n_a_t_s_1_1_client_1_1_conn_js_sub_event_args.html", "class_n_a_t_s_1_1_client_1_1_conn_js_sub_event_args" ],
        [ "DefaultUserJWTHandler", "class_n_a_t_s_1_1_client_1_1_default_user_j_w_t_handler.html", "class_n_a_t_s_1_1_client_1_1_default_user_j_w_t_handler" ],
        [ "EncodedConnection", "class_n_a_t_s_1_1_client_1_1_encoded_connection.html", "class_n_a_t_s_1_1_client_1_1_encoded_connection" ],
        [ "EncodedMessageEventArgs", "class_n_a_t_s_1_1_client_1_1_encoded_message_event_args.html", "class_n_a_t_s_1_1_client_1_1_encoded_message_event_args" ],
        [ "ErrEventArgs", "class_n_a_t_s_1_1_client_1_1_err_event_args.html", "class_n_a_t_s_1_1_client_1_1_err_event_args" ],
        [ "FlowControlProcessedEventArgs", "class_n_a_t_s_1_1_client_1_1_flow_control_processed_event_args.html", null ],
        [ "HeartbeatAlarmEventArgs", "class_n_a_t_s_1_1_client_1_1_heartbeat_alarm_event_args.html", null ],
        [ "IAsyncSubscription", "interface_n_a_t_s_1_1_client_1_1_i_async_subscription.html", "interface_n_a_t_s_1_1_client_1_1_i_async_subscription" ],
        [ "IConnection", "interface_n_a_t_s_1_1_client_1_1_i_connection.html", "interface_n_a_t_s_1_1_client_1_1_i_connection" ],
        [ "IEncodedConnection", "interface_n_a_t_s_1_1_client_1_1_i_encoded_connection.html", "interface_n_a_t_s_1_1_client_1_1_i_encoded_connection" ],
        [ "IStatistics", "interface_n_a_t_s_1_1_client_1_1_i_statistics.html", "interface_n_a_t_s_1_1_client_1_1_i_statistics" ],
        [ "ISubscription", "interface_n_a_t_s_1_1_client_1_1_i_subscription.html", "interface_n_a_t_s_1_1_client_1_1_i_subscription" ],
        [ "ISyncSubscription", "interface_n_a_t_s_1_1_client_1_1_i_sync_subscription.html", "interface_n_a_t_s_1_1_client_1_1_i_sync_subscription" ],
        [ "Msg", "class_n_a_t_s_1_1_client_1_1_msg.html", "class_n_a_t_s_1_1_client_1_1_msg" ],
        [ "MsgHandlerEventArgs", "class_n_a_t_s_1_1_client_1_1_msg_handler_event_args.html", "class_n_a_t_s_1_1_client_1_1_msg_handler_event_args" ],
        [ "MsgHeader", "class_n_a_t_s_1_1_client_1_1_msg_header.html", "class_n_a_t_s_1_1_client_1_1_msg_header" ],
        [ "NATSBadSubscriptionException", "class_n_a_t_s_1_1_client_1_1_n_a_t_s_bad_subscription_exception.html", null ],
        [ "NATSConnectionClosedException", "class_n_a_t_s_1_1_client_1_1_n_a_t_s_connection_closed_exception.html", null ],
        [ "NATSConnectionDrainingException", "class_n_a_t_s_1_1_client_1_1_n_a_t_s_connection_draining_exception.html", null ],
        [ "NATSConnectionException", "class_n_a_t_s_1_1_client_1_1_n_a_t_s_connection_exception.html", null ],
        [ "NATSException", "class_n_a_t_s_1_1_client_1_1_n_a_t_s_exception.html", null ],
        [ "NATSInvalidHeaderException", "class_n_a_t_s_1_1_client_1_1_n_a_t_s_invalid_header_exception.html", null ],
        [ "NATSJetStreamClientException", "class_n_a_t_s_1_1_client_1_1_n_a_t_s_jet_stream_client_exception.html", null ],
        [ "NATSJetStreamStatusException", "class_n_a_t_s_1_1_client_1_1_n_a_t_s_jet_stream_status_exception.html", null ],
        [ "NATSMaxMessagesException", "class_n_a_t_s_1_1_client_1_1_n_a_t_s_max_messages_exception.html", null ],
        [ "NATSMaxPayloadException", "class_n_a_t_s_1_1_client_1_1_n_a_t_s_max_payload_exception.html", null ],
        [ "NATSNoRespondersException", "class_n_a_t_s_1_1_client_1_1_n_a_t_s_no_responders_exception.html", null ],
        [ "NATSNoServersException", "class_n_a_t_s_1_1_client_1_1_n_a_t_s_no_servers_exception.html", null ],
        [ "NATSNotSupportedException", "class_n_a_t_s_1_1_client_1_1_n_a_t_s_not_supported_exception.html", null ],
        [ "NATSProtocolException", "class_n_a_t_s_1_1_client_1_1_n_a_t_s_protocol_exception.html", null ],
        [ "NATSReconnectBufferException", "class_n_a_t_s_1_1_client_1_1_n_a_t_s_reconnect_buffer_exception.html", null ],
        [ "NATSSecureConnRequiredException", "class_n_a_t_s_1_1_client_1_1_n_a_t_s_secure_conn_required_exception.html", null ],
        [ "NATSSecureConnWantedException", "class_n_a_t_s_1_1_client_1_1_n_a_t_s_secure_conn_wanted_exception.html", null ],
        [ "NATSSlowConsumerException", "class_n_a_t_s_1_1_client_1_1_n_a_t_s_slow_consumer_exception.html", null ],
        [ "NATSStaleConnectionException", "class_n_a_t_s_1_1_client_1_1_n_a_t_s_stale_connection_exception.html", null ],
        [ "NATSTimeoutException", "class_n_a_t_s_1_1_client_1_1_n_a_t_s_timeout_exception.html", null ],
        [ "NkeyPair", "class_n_a_t_s_1_1_client_1_1_nkey_pair.html", "class_n_a_t_s_1_1_client_1_1_nkey_pair" ],
        [ "Nkeys", "class_n_a_t_s_1_1_client_1_1_nkeys.html", null ],
        [ "NUID", "class_n_a_t_s_1_1_client_1_1_n_u_i_d.html", "class_n_a_t_s_1_1_client_1_1_n_u_i_d" ],
        [ "Options", "class_n_a_t_s_1_1_client_1_1_options.html", "class_n_a_t_s_1_1_client_1_1_options" ],
        [ "ReconnectDelayEventArgs", "class_n_a_t_s_1_1_client_1_1_reconnect_delay_event_args.html", "class_n_a_t_s_1_1_client_1_1_reconnect_delay_event_args" ],
        [ "Statistics", "class_n_a_t_s_1_1_client_1_1_statistics.html", "class_n_a_t_s_1_1_client_1_1_statistics" ],
        [ "StatusEventArgs", "class_n_a_t_s_1_1_client_1_1_status_event_args.html", null ],
        [ "StringUserJWTHandler", "class_n_a_t_s_1_1_client_1_1_string_user_j_w_t_handler.html", "class_n_a_t_s_1_1_client_1_1_string_user_j_w_t_handler" ],
        [ "Subscription", "class_n_a_t_s_1_1_client_1_1_subscription.html", "class_n_a_t_s_1_1_client_1_1_subscription" ],
        [ "SyncSubscription", "class_n_a_t_s_1_1_client_1_1_sync_subscription.html", "class_n_a_t_s_1_1_client_1_1_sync_subscription" ],
        [ "UnhandledStatusEventArgs", "class_n_a_t_s_1_1_client_1_1_unhandled_status_event_args.html", null ],
        [ "UserJWTEventArgs", "class_n_a_t_s_1_1_client_1_1_user_j_w_t_event_args.html", "class_n_a_t_s_1_1_client_1_1_user_j_w_t_event_args" ],
        [ "UserSignatureEventArgs", "class_n_a_t_s_1_1_client_1_1_user_signature_event_args.html", "class_n_a_t_s_1_1_client_1_1_user_signature_event_args" ]
      ] ]
    ] ]
];