stages:
- stage: Build
  jobs:
  - job: BuildArtifacts
    displayName: 'Builds, tests & produces artifacts'
    timeoutInMinutes: 60
    cancelTimeoutInMinutes: 5
    steps:
    - task: NugetToolInstaller@1
    - task: DotNetCoreCLI@2
      inputs:
        command: restore
        projects: 'src/*.sln'
    - task: DotNetCoreCLI@2
      displayName: 'Build Solution'
      inputs:
        command: build
        projects: 'src/*.sln'
        arguments: '-c $(BuildConfiguration) --no-incremental --nologo -p:TreatWarningsAsErrors=true -p:Version=$(SemVer) -p:InformationalVersion=$(InfoVer)'
  
    - task: VSTest@2
      displayName: 'UnitTests Net Standard 2.0'
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: 'src/Tests/UnitTests/bin/$(BuildConfiguration)/net462/UnitTests.dll'
        configuration: $(BuildConfiguration)
        testRunTitle: 'UnitTests Net Standard 2.0'
  
    - task: PowerShell@2
      displayName: 'Install Dependencies'
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Getting server executable."
          $nats = "$(Agent.TempDirectory)\nats"
          New-Item -ItemType "directory" -Path $nats
          wget https://github.com/nats-io/nats.client.deps/raw/main/win-latest/nats-server.exe -outfile $nats\nats-server.exe
          Write-Host "Appending nats-server directory $nats to path."
          Write-Host "##vso[task.setvariable variable=PATH;]${env:PATH};$nats"

    - task: VSTest@2
      displayName: 'IntegrationTests Net Standard 2.0'
      env:
        GODEBUG: x509sha1=1
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: 'src/Tests/IntegrationTests/bin/$(BuildConfiguration)/net462/IntegrationTests.dll'
        configuration: $(BuildConfiguration)
        rerunFailedTests: True
        rerunMaxAttempts: 2
        testRunTitle: 'IntegrationTests Net Standard 2.0'

    - task: VSTest@2
      displayName: 'IntegrationTests Internal Net Standard 2.0'
      env:
        GODEBUG: x509sha1=1
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: 'src/Tests/IntegrationTestsInternal/bin/$(BuildConfiguration)/net462/IntegrationTestsInternal.dll'
        configuration: $(BuildConfiguration)
        rerunFailedTests: True
        rerunMaxAttempts: 2
        testRunTitle: 'IntegrationTests Internal Net Standard 2.0'
        
    - task: DotNetCoreCLI@2
      displayName: 'Pack Nupkg'
      inputs:
        command: custom
        custom: pack
        projects: 'src/*.sln'
        arguments: '-c $(BuildConfiguration) --no-build -o $(Build.ArtifactStagingDirectory) -p:Version=$(SemVer) -p:InformationalVersion=$(InfoVer)'
  
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifacts'
      inputs:
        path: '$(Build.ArtifactStagingDirectory)'
        artifact: Artifacts
